---
# SECRET PROVIDER CLASS
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: spc-kv-prd-titan-230101
  namespace: titan
spec:
  provider: azure

#================================================================================================
# Mounted Files - These secrets can be mounted in pods as files.
#================================================================================================

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.global.userAssignedIdentityID }}
    tenantId: {{ .Values.global.tenantId }}
    keyvaultName: {{ .Values.global.keyvaultName }}
    objects: |
      array:
        - |
          objectName: titan-username
          objectType: secret
          objectVersion: ""
        - |
          objectName: titan-password
          objectType: secret
          objectVersion: ""

#================================================================================================
# Environment Variables - These secrets can be mounted in pods as environment variables.
#================================================================================================

  secretObjects:
  - secretName: so-titan
    type: Opaque
    data:
    - objectName: titan-username
      key: titan_username
    - objectName: titan-password
      key: titan_password

---
